# Sever
server:
  port: 8887

# Registry Client
eureka:
   client:
      fetch-registry: true
      serviceUrl:
         defaultZone: http://localhost:8889/eureka
           
# Matricula de Microservicios
spring:
  cloud:
    gateway:
      discovery.locator:
          enabled: true
          lowerCaseServiceId: true

# Activacion de endpoints
management:
     endpoints:
       web:
         exposure:
           include: '*'
     endpoint:
       gateway:
          enabled: true
       health:
         show-details: always